version: '3'

networks:
  nginx:
    external: true

services:
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "82:81"
      - "443:443"
    #    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vhosts:/etc/nginx/conf.d
      - ./apps:/var/www
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/:/etc/nginx/ssl:ro
    restart: always
    container_name: nginx
    networks:
      - nginx

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx
